library/urls.py
from . import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import include
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stuff/', include('stuff.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^accounts/', include('account.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'', include('catalog.urls')),
    # url('/', RedirectView.as_view(url='/catalog/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf.urls import url
from . import views

app_name = 'order'

urlpatterns = [
    url('^$', views.OrderBookView.as_view(), name='your_books')
]

stuff/urls.py
from django.conf.urls import url
from . import views

app_name = 'stuff'

urlpatterns = [
    url(r'^author/create/$', views.AuthorCreateView.as_view(), name='author_create'),
    url(r'^book/create/$', views.BookCreateView.as_view(), name='book_create'),
    url(r'^author/(?P<slug>[-\w]+)/update/$', views.AuthorUpdateView.as_view(), name='author_update'),
    url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdateView.as_view(), name='book_update'),
    url(r'^author/(?P<slug>[-\w]+)/delete/$', views.AuthorDeleteView.as_view(), name='author_delete'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDeleteView.as_view(), name='book_delete'),
]

stuff/models.py
from django.db import models

# Create your models here.

stuff/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from catalog.models import Author, Book
from django.views.generic.base import View


class AuthorCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'stuff/author_form.html'
    permission_required = 'catalog.can_mark_returned'
    model = Author
    fields = '__all__'


class BookCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'stuff/book_form.html'
    permission_required = 'catalog.can_mark_returned'
    model = Book
    fields = '__all__'


class AuthorUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'stuff/author_form.html'
    permission_required = 'catalog.can_mark_returned'
    model = Author
    fields = ['date_of_dead']

class BookUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'stuff/book_form.html'
    permission_required = 'catalog.can_mark_returned'
    model = Author
    fields = '__all__'


class AuthorDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'stuff/author_delete.html'
    permission_required = 'catalog.can_mark_returned'
    model = Author
    template_name_suffix = '_delete'
    success_url = reverse_lazy('catalog:author_list')


class BookDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'stuff/book_delete.html'
    permission_required = 'catalog.can_mark_returned'
    model = Book
    success_url = reverse_lazy('catalog:book_list')

stuff/templates/stuff/author_delete.html
{% extends "catalog/base.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

stuff/templates/stuff/author_form.html
{% extends "catalog/base.html" %}

{% block content %}
<h2>Введите данные в поля</h2>
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

stuff/templates/stuff/book_delete.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}  {% endblock %}


{% block content %}
<h1>Delete Author</h1>

<p>Дйствительно удалить книгу: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да, удалить" />
</form>

{% endblock %}

stuff/templates/stuff/book_form.html
{% extends "catalog/base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

stuff/templates/stuff/stuff_gate.html
{% extends "catalog/base.html" %}

{% block content %}
    <h2> Создание, редактирование и удаление.</h2>
    <ul>
        <li><a href="{% url 'stuff:author_create'%}">Создать автора</a></li>
        <li><a href="{% url 'stuff:book_create'%}">Создать книгу</a></li>
        <li><a href="{% url 'stuff:author_update'%}">Обновить автора</a></li>
        <li><a href="{% url 'stuff:author_delete'%}">Удалить автора</a></li>
        <li><a href="{% url 'stuff:book_delete'%}">Удалить книгу</a></li>
    </ul>
{% endblock %}