catalog/urls.py
from django.conf.urls import url
from . import views

app_name = 'catalog'

urlpatterns = [
    url(r'^book_reserve/$', views.book_reserve, name='book_reserve'),
    url(r'^author/$', views.AuthorListView.as_view(), name='author_list'),
    url(r'^search_result/$', views.SearchView.as_view(), name='search'),
    url(r'^genre/$', views.GenreListView.as_view(), name='genre_list'),
    url(r'^genre_filter_result/(?P<slug>[-\w]+)/$', views.GenreFilterView.as_view(), name='genre_filter'),
    url(r'^$', views.BookListView.as_view(), name='book_list'),
    url(r'^author/(?P<slug>[-\w]+)/$', views.AuthorDetailView.as_view(), name='author_detail'),
    url(r'^(?P<slug>[-\w]+)/$', views.BookDetailView.as_view(), name='book_detail'),

]

library/urls.py
from . import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import include
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stuff/', include('stuff.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^accounts/', include('account.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'', include('catalog.urls')),
    # url('/', RedirectView.as_view(url='/catalog/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf.urls import url
from . import views

app_name = 'order'

urlpatterns = [
    url('^$', views.OrderBookView.as_view(), name='your_books')
]

stuff/urls.py
from django.conf.urls import url
from . import views

app_name = 'stuff'

urlpatterns = [
    url(r'^author/create/$', views.AuthorCreateView.as_view(), name='author_create'),
    url(r'^book/create/$', views.BookCreateView.as_view(), name='book_create'),
    url(r'^author/(?P<slug>[-\w]+)/update/$', views.AuthorUpdateView.as_view(), name='author_update'),
    url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdateView.as_view(), name='book_update'),
    url(r'^author/(?P<slug>[-\w]+)/delete/$', views.AuthorDeleteView.as_view(), name='author_delete'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDeleteView.as_view(), name='book_delete'),
]

catalog/models.py
import uuid
from datetime import date
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название жанра')
    slug = models.SlugField(max_length=100)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def genre_filter(self):
        return reverse('catalog:genre_filter', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=100, verbose_name='Язык')

    class Meta:
        verbose_name = 'Язык'
        verbose_name_plural = 'Языки'

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, verbose_name='Слаг')
    authors = models.ForeignKey('Author', verbose_name='Автор', on_delete=models.CASCADE)
    summary = models.TextField(max_length=1000, verbose_name='Описание')
    cover = models.FileField(upload_to='book_cover/%Y/%m/%d/', default='img/no-image.jpg')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, verbose_name='Жанр')
    language = models.ForeignKey(Language, on_delete=models.CASCADE, verbose_name='Язык')

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:book_detail', kwargs={'slug': self.slug})

    def book_delete(self):
        return reverse('stuff:book_delete', kwargs={'pk': self.pk})

    def book_update(self):
        return reverse('stuff:book_update', kwargs={'pk': self.pk})


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique key for this particular key')
    book = models.ForeignKey(Book, verbose_name='Книга', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=100, verbose_name='Издательство')
    ISBN = models.CharField('ISBN', max_length=100)
    return_date = models.DateField(null=True, blank=True, verbose_name='Дата возврата книги')

    loan_status = (
        ('m', 'maintains'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(max_length=1, choices=loan_status, default='m', blank=True, help_text='Book availability')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        ordering = ['return_date']
        verbose_name = 'Экземпляр книги'
        verbose_name_plural = 'Экземпляр книг'
        permissions = (('can_mark_returned', 'Set book as returned'),)

    def __str__(self):
        return '{} {}'.format(self.id, self.book.title)

    @property
    def is_overdue(self):
        if self.return_date and date.today() > self.return_date:
            return True
        return False

    def reserved_book(self):
        return reverse('catalog:reserved_book', kwargs={'pk': self.pk})


class Author(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя автора')
    slug = models.SlugField(max_length=100, verbose_name='Слаг', blank=True)
    photo = models.ImageField(upload_to='author_photo/%Y/%m/%d/', default='img/no-image.jpg', blank=True)
    date_of_birth = models.DateField(verbose_name='Дата рождения', blank=True)
    date_of_dead = models.DateField(verbose_name='Дата смерти', blank=True)
    books = models.ManyToManyField(Book, verbose_name='Книги', blank=True)

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def get_absolute_url(self):
        return reverse('catalog:author_detail', kwargs={'slug': self.slug})

    def delete_author(self):
        return reverse('stuff:author_delete', kwargs={'slug': self.slug})

    def update_author(self):
        return reverse('stuff:author_update', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms


class BookReserveForm(forms.Form):
    approve = forms.CheckboxInput()
    text = forms.Textarea()

catalog/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin

from catalog.forms import BookReserveForm
from .models import Book, Author, BookInstance, Genre


# Create your views here.
class BookListView(ListView):
    template_name = 'catalog/book_list.html'
    model = Book

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        num_visits = self.request.session.get('num_visits', 0)
        self.request.session['num_visits'] = num_visits + 1
        context['visits'] = self.request.session['num_visits']
        return context


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'
    form_class = BookReserveForm

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['book_instance'] = BookInstance.objects.filter(book__slug=self.kwargs['slug'], status='m')
        return context



def book_reserve(request):

    current_book = request.POST.get('book_id')
    book = Book.objects.get(id=current_book)
    slug = book.slug
    book_instance = BookInstance.objects.filter(book=book, status='m').first()
    book_instance.status = 'r'
    book_instance.borrower = request.user
    book_instance.save()
    return redirect("catalog:book_detail", slug=slug)

class AuthorListView(ListView):
    model = Author
    context_object_name = 'author'
    template_name = 'catalog/author_list.html'


class AuthorDetailView(DetailView):
    model = Author
    context_object_name = 'author'

class GenreListView(ListView):
    model = Genre
    template_name = 'catalog/genre_list.html'
    context_object_name = 'genre'

class GenreFilterView(ListView):
    template_name = 'catalog/genre_filter.html'
    model = Book
    def get_context_data(self, *, object_list=None, **kwargs):
        print(self.kwargs['slug'])
        context = super(GenreFilterView, self).get_context_data(**kwargs)
        context['book_data'] = Book.objects.filter(genre__slug=self.kwargs['slug'])
        return context


class SearchView(ListView):
    template_name = 'catalog/search_result.html'
    model = Book

    def get_queryset(self):
        query = self.request.GET.get('user_input')
        book_data = Book.objects.filter(Q(title__icontains=query) | Q(summary__icontains=query)
                                        | Q(genre__name__icontains=query) | Q(author__name__icontains=query)
                                        | Q(language__name__icontains=query))

        return book_data

catalog/templates/catalog/author_detail.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}  {% endblock %}

{% block content %}
<div id="sidebar" class="col-sm-3">
    <h3></h3>
    <ul>
        <li class="selected" >
          <a href="#">ВСЕ</a>
        </li>

       <li>1</li>
       <li>1</li>
       <li>1</li>
       <li>1</li>
       <li>
            <form method="get" action="{% url 'catalog:search' %}">
                  <input type="search" name="user_input" class="form-control"><input class="form-control" type="submit" value="Поиск">
            </form>
       </li>

    </ul>
</div>
 <div id="main" class="product_list col-sm-9">
    <div class="item row">
            <img src="{{author.photo.url}}" alt="No Image Sorry">
            <p><strong>Имя: </strong>{{author.name}}</p>
            <p><strong>Родился:</strong>{{author.date_of_birth}}</p>
            <p><strong>Умер:</strong>{{author.date_of_dead}}</p>
            <p><strong>Книги:</strong>{{author.books}}</p>
        </div>

    </div>
  </div>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}  {% endblock %}

{% block content %}
<div id="sidebar" class="col-sm-3">
    <h3></h3>
    <ul>
        <li class="selected">
          <a href="#">ВСЕ</a>
        </li>

        <li><a>По жанрам</a></li>
       <li><a>По алфавиту</a></li>
       <li><a>По дате рождения</a></li>
       <li><a>По дате смерти</a></li>
       <li>
            <form method="get" action="{% url 'catalog:search' %}">
                  <input type="search" name="user_input" class="form-control"><input class="form-control" type="submit" value="Поиск">
            </form>
       </li>

    </ul>
</div>
<div class="main col-sm-9">
        <div class="author_list">
            {% for single_author in author%}

                <p><a href="{{ single_author.get_absolute_url }}">{{ single_author.name}}</a></p>
                {% if perm.catalog.can_mark_returned %}
                    <a href="{{single_author.update_author}}"><input type="submit" value="Редактировать"></a>
                    <a href="{{single_author.delete_author}}"><input type="submit" value="Удалить"></a>
                {% endif %}

            {% endfor %}
        </div>
</div>
{% endblock %}

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    {% load staticfiles %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon_book.png'%}" type="image/x-icon">
    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
  <main>
    <header>
        <div class="top">
            <div class="top-item top_left_font">
                <a href="{% url 'catalog:book_list'%}">Online Библиотека</a>
            </div >
            <div class="top-item">

                <p> Ваш IP {{geodata.ip}}</p>
                {% if user.is_authenticated %}
                    <p>Пользователь: {{user.get_username}}</p>
                    <a href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
                {% else %}
                    <a href="{% url 'login' %}?next={{request.path}}">Войти</a>
                    <a href="{% url 'sign_up' %}">Зарегистрироваться</a>
                {% endif %}
            </div>
        </div>
        <nav>
             <div class="btn-toolbar top-bl menu" role="toolbar" aria-label="Toolbar with button groups">
                  <div class="btn-group mr-2" role="group" aria-label="First group">
                        <a class="btn btn-danger" href="{% url 'catalog:book_list'%}">КНИГИ</a>
                        <a class="btn btn-danger" href="{% url 'catalog:author_list' %}">АВТОРЫ</a>
                        <a class="btn btn-danger" href="{% url 'catalog:genre_list' %}">ЖАНРЫ</a>

              </div>
              <div class="btn-group mr-2" role="group" aria-label="Second group">
                    {% if user.is_authenticated and not  perms.catalog.can_make_returned %}
                        <a class="btn btn-success" href="{% url 'order:your_books' %}">МОИ КНИГИ </a>
                    {% endif %}
              </div>
              <div class="btn-group" role="group" aria-label="Third group">

                    {% if perms.catalog.can_make_returned %}
                    {% endif %}
              </div>
            </div>
        </nav>
    </header>

    <section id="content">
      {% block content %}{% endblock %}
     </section>
  </main>

</body>
</html>

catalog/templates/catalog/book_detail.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}  {% endblock %}

{% block content %}
<div id="sidebar" class="col-sm-3">

    <ul>
        <li class="selected" >
          <a href="#">ВСЕ</a>
        </li>
        <li>1</li>
        <li>1</li>
        <li>1</li>
        <li>1</li>
        <li>
            <form method="get" action="{% url 'catalog:search' %}">
                  <input type="search" name="user_input" class="form-control"><input class="form-control" type="submit" value="Поиск">
            </form>
        </li>
    </ul>
</div>
<div id="main" class="col-sm-9">
    <div class="book_detail">
        <div class="book_detail__item">
            <img src="{{book.cover.url}}" alt="No Image Sorry">
        </div>
        <div class="book_detail__item">
            <p><strong>Автор: </strong> {{book.authors}}</p>
            <p><strong>Описание: </strong> {{book.summary}}</p>
            <p><strong>Жанр: </strong> {{book.genre}}</p>
            <p><strong>Язык: </strong> {{book.language}}</p>
            <p><strong>Количество доступных книг: </strong> {{book_instance.count}}</p>
            {% if user.is_authenticated and not perm.catalog.can_mark_returned %}
                <form method="POST" action="{% url 'catalog:book_reserve' %}">
                    {% csrf_token %}
                    <input type="hidden" name="book_id" value="{{book.id}}">
                    <input type="submit" name="reserve" value="Взять книгу">
                </form>
            {% endif %}

            {% if perm.catalog.can_mark_returned%}
            <a href="{{book.book_delete}}"><input type="submit" value="Удалить книгу"></a>

            {% endif %}

        </div>

        </div>
</div>


{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}  {% endblock %}

{% block content %}
<div id="sidebar" class="col-sm-3">

    <ul>
        <li class="selected" >
          <a href="#">ВСЕ</a>
        </li>

        <li>Количество посещений страницы {{visits}}</li>
        <li>
            {% if perms.catalog.can_make_returned %}
                <a href="{% url 'stuff:book_create' %}"><input type="submit" value="Добавить книгу"></a>
                <a href="{% url 'stuff:author_create'%}"><input type="submit" value="Добавить автора"></a>
            {% endif %}
        </li>

       <li>
            <form method="get" action="{% url 'catalog:search' %}">
                  <input type="search" name="user_input" class="form-control"><input class="form-control" type="submit" value="Поиск">
            </form>
       </li>


        <h2>Наш офис</h2>


    </ul>
</div>
<div class="main col-sm-9">
    {% for book in book_list%}
    <div class="gallery">
        <a  class="gallery__link" href="{{book.get_absolute_url}}">
            {% if book.cover %} <img class="gallery__img" src="{{book.cover.url}}" > {% else %} <img src="{% static 'img/no-image.jpg' %}"> {%endif%}
        </a>
        <p class="gallery__paragraph">{{book.authors}}</p>
        <a class="gallery__link" href="{{book.get_absolute_url}}">{{book.title}}</a>

                    {% if perms.catalog.can_make_returned %}
                        <div class="gallery__input">
                            <a  href="{{book.book_update}}"><input type="submit" value="Редактировать"></a>
                            <a   href="{{book.book_delete}}"><input type="submit" value="Удалить "></a>
                        </div>
                    {% endif %}

    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/genre_filter.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}  {% endblock %}

{% block content %}
<div id="sidebar" class="col-sm-3">

    <ul>
        <li class="selected" >
          <a href="#">ВСЕ</a>
        </li>

        <li>Количество посещений страницы {{visits}}</li>
        <li>
            {% if perms.catalog.can_make_returned %}
                <a href="{% url 'stuff:book_create' %}"><input type="submit" value="Добавить книгу"></a>
                <a href="{% url 'stuff:author_create'%}"><input type="submit" value="Добавить автора"></a>
            {% endif %}
        </li>

       <li>
            <form method="get" action="{% url 'catalog:search' %}">
                  <input type="search" name="user_input" class="form-control"><input class="form-control" type="submit" value="Поиск">
            </form>
       </li>


        <h2>Наш офис</h2>


    </ul>
</div>
<div class="main col-sm-9">
    {% for book in book_data%}
    <div class="gallery">
        <a  class="gallery__link" href="{{book.get_absolute_url}}">
            {% if book.cover %} <img class="gallery__img" src="{{book.cover.url}}" > {% else %} <img src="{% static 'img/no-image.jpg' %}"> {%endif%}
        </a>
        <p class="gallery__paragraph">{{book.authors}}</p>
        <a class="gallery__link" href="{{book.get_absolute_url}}">{{book.title}}</a>

                    {% if perms.catalog.can_make_returned %}
                        <div class="gallery__input">
                            <a  href="{{book.book_update}}"><input type="submit" value="Редактировать"></a>
                            <a   href="{{book.book_delete}}"><input type="submit" value="Удалить "></a>
                        </div>
                    {% endif %}

    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/genre_list.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}  {% endblock %}

{% block content %}
<div id="sidebar" class="col-sm-3">

    <ul>
        <li class="selected" >
          <a href="#">ВСЕ</a>
        </li>
        <li>1</li>
        <li>1</li>
        <li>1</li>
        <li>1</li>
        <li><input type="search" name="query" class="form-control"><input class="form-control" type="submit" value="Поиск"></li>
    </ul>
</div>
<div id="main" class="col-sm-9">
    <div class="book_detail">
        <div class="book_item1">
            {% for item in genre %}
            <p>
                <a href="{{item.genre_filter}}">
                    {{ item }}
                </a>
            </p>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

catalog/templates/catalog/search_result.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}  {% endblock %}

{% block content %}
<div id="sidebar" class="col-sm-3">

    <ul>
        <li class="selected" >
          <a href="#">ВСЕ</a>
        </li>
        <li>1</li>
        <li>1</li>
        <li>1</li>
        <li>1</li>
        <li>
            <form method="get" action="{% url 'catalog:search' %}">
                  <input type="search" name="user_input" class="form-control"><input class="form-control" type="submit" value="Поиск">
            </form>
        </li>
    </ul>
</div>
<div id="main" class="col-sm-9">
    <div class="book_detail">
        <div class="book_item1">
            {{ object_list }}
            {% for book in object_list %}

                    <div class="book_detail">
        <div class="book_detail__item">
            <img src="{{book.cover.url}}" alt="No Image Sorry">
        </div>
        <div class="book_detail__item">
            <p><strong>Автор: </strong> {{book.authors}}</p>
            <p><strong>Описание: </strong> {{book.summary}}</p>
            <p><strong>Жанр: </strong> {{book.genre}}</p>
            <p><strong>Язык: </strong> {{book.language}}</p>
            <p><strong>Количество доступных книг: </strong> {{book_instance.count}}</p>
            {% if user.is_authenticated and not perm.catalog.can_mark_returned %}

                <a href="{{book.book_reserved}}"><input name='reserved' type="submit" value="Взять книгу"></a>

            {% endif %}

            {% if perm.catalog.can_mark_returned%}
            <a href="{{book.book_delete}}"><input type="submit" value="Удалить книгу"></a>

            {% endif %}

        </div>

        </div>


        {% endfor %}
        </div>
    </div>
</div>


{% endblock %}